
name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  qa-job:
    name: Test
    runs-on: ubuntu-latest
    needs: build-job

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

  stage-deploy-job:
    name: Deploy to Staging
    needs: qa-job
    runs-on: ubuntu-latest
    environment: 
      name: Stage
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    
  prod-deploy-job:
    name: Deploy to Production
    needs: stage-deploy-job
    runs-on: ubuntu-latest
    environment: 
      name: Prod
      url: 'https://teams.microsoft.com/l/app/468a6043-0d15-4c63-8d4f-44cc0e0f6473'
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    
